---
title: "03.2b_plot-gene-coexpression.Rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup 

```{r}

"%&%" <- function(a,b) paste0(a,b)
library("tidyverse")
library("GenomicRanges")
library("viridis")
library("data.table")
library("plyr")

serv.dir <- "/home/jason/science/servers/FUSE5/"
proj.dir <- serv.dir %&% "projects/t2d_classification/"

work.dir <- proj.dir %&% "revamp/"
analysis.dir <- work.dir %&% "analysis_files/"
plot.dir <- work.dir %&% "plots/"

count.df1 <- fread(work.dir%&%"analysis_files/classifier_counts.txt")
count.df2 <- fread(work.dir%&%"analysis_files/classifier_counts_with-shared.txt")

```


```{r}

simpleCap <- function(x) {
  s <- strsplit(x, " ")[[1]]
  paste(toupper(substring(s, 1,1)), substring(s, 2),
      sep="", collapse=" ")
}

append_classifer_counts <- function(w.df, count.df){
  names(count.df) <- names(count.df) %>% tolower(.)  
  names(count.df)[1] <- names(count.df)[1] %>% simpleCap(.)
  w.df$classifer.count <- map(1:dim(w.df)[1],function(i){
    row.df <- w.df[i,]
    count <- filter(count.df,Threshold==row.df$threshold) %>% 
     dplyr::select(.,one_of(as.character(unique(row.df$geneset)))) %>% as.integer(.)
    if (row.df$geneset=="peripheral"){
     count <- filter(count.df,Threshold==row.df$threshold) %>% 
        dplyr::select(.,one_of("adipose","liver","muscle")) %>% sum(.)  
    }
  return(count)
}) %>% as.integer(.)  
  return(w.df)
}

```



```{r}

w.df <- fread(analysis.dir %&% "coexpress-enrich_weighted_p10Coding.txt") %>% 
  na.omit(.) %>% append_classifer_counts(.,count.df1)

w.df2 <- fread(analysis.dir %&%
                 "coexpress-enrich_weighted_p10Coding_with-shared.txt") %>% 
  na.omit(.) %>% append_classifer_counts(.,count.df2)

```



```{r}

plot_enrich <- function(plot.df,nrow1=FALSE){
  plt <- ggplot(data=plot.df,aes(x=tissue,y=enrich.factor)) + 
    geom_point(aes(size=classifer.count,shape=geneset,fill=log_pval),
               alpha=0.7) 
  if (nrow1==TRUE){
    plt <- plt + facet_wrap(~threshold,nrow=1)
  } else{
    plt <- plt + facet_wrap(~threshold)
  }
  plt <- plt + scale_shape_manual(name="Gene set",values=c(21,22,23,24)) +
    scale_fill_viridis(name="-log10(p)",direction = -1) + 
    ylab("Enrichment") + xlab("Tissue") + 
    theme(axis.text.x=element_text(size=14),
          strip.text = element_text(size=17),
          axis.title=element_text(size=17),
          legend.key.size = unit(7,"line")) + 
    scale_size(range=c(1,3.5),limits=c(0,250)) + 
    coord_flip() + 
    theme_bw()
  return(plt)
}


plot_enrich_alt1 <- function(plot.df){
  plt <- ggplot(data=plot.df,aes(x=tissue,y=enrich.factor)) + 
    geom_point(aes(size=classifer.count,shape=geneset,fill=log_pval),
               alpha=0.7) 

  plt <- plt + facet_wrap(~threshold)
  plt <- plt + 
    scale_shape_manual(name="Gene set",
      values=c(21,22,23,24,25,4)) +
    scale_fill_viridis(name="-log10(p)",direction = -1) + 
    ylab("Enrichment") + xlab("Tissue") + 
    theme_bw() + 
    theme(axis.text.x=element_text(size=12,angle=30,vjust=0.5),
          strip.text = element_text(size=20),
          axis.title=element_text(size=12),
          legend.key.size = unit(1,"line")) + 
          #panel.grid = element_blank()) + 
    scale_size(range=c(1,12),limits=c(0,350)) + 
    coord_flip()
  return(plt)
}



plot_enrich_alt <- function(plot.df,nrow1=FALSE){
  plt <- ggplot(data=plot.df,aes(x=tissue,y=enrich.factor)) + 
    geom_point(aes(size=classifer.count,shape=geneset,fill=log_pval),
               alpha=0.7) 
  if (nrow1==TRUE){
    plt <- plt + facet_wrap(~threshold,nrow=1)
  } else{
    plt <- plt + facet_wrap(~threshold)
  }
  plt <- plt + 
    scale_shape_manual(name="Gene set",
      values=c(21,22,23,24,25,4)) +
    scale_fill_viridis(name="-log10(p)",direction = -1) + 
    ylab("Enrichment") + xlab("Tissue") + 
    theme_bw() + 
    theme(axis.text.x=element_text(size=12,angle=30,vjust=0.5),
          strip.text = element_text(size=12),
          axis.title=element_text(size=12),
          legend.key.size = unit(1,"line"),
          panel.grid = element_blank()) + 
    scale_size(range=c(1,12),limits=c(0,350))# + 
  return(plt)
}

plot_enrich_alt2 <- function(plot.df){
  plt <- ggplot(data=plot.df,aes(x=tissue,y=enrich.factor)) + 
    geom_point(aes(size=classifer.count,shape=geneset,fill=log_pval),
               alpha=0.7) 

  plt <- plt + facet_wrap(~threshold,nrow=1)
  plt <- plt + 
    scale_shape_manual(name="Gene set",
      values=c(21,22,23,24,25,4)) +
    #scale_fill_continuous(guide = guide_legend(nrow=1)) + 
    scale_fill_viridis(name="-log10(p)",direction = -1,
                       guide = guide_legend(nrow=1)) + 
    ylab("Enrichment") + xlab("Tissue") + 
    theme_bw() + 
    theme(axis.text.x=element_text(size=8,angle=30,vjust=0.5),
          strip.text = element_text(size=10),
          axis.title=element_text(size=12),
          legend.key.size = unit(1,"line")) + 
    scale_size(range=c(1,8),limits=c(0,350)) + 
    coord_flip() 
  return(plt)
}

```


# Filtering 

```{r}

plt1 <- plot_enrich(w.df)
ggsave(plot=plt1,filename = plot.dir %&% "coexpress-enrich_weighted-p10Coding.png",width=12,height=12)
pltS <- plot_enrich_alt1(w.df2)
ggsave(plot=pltS,filename = plot.dir %&% "coexpress-enrich_weighted-p10Coding_with-shared.png",
       width=10,height=15)
ggsave(plot=pltS,filename = plot.dir %&% "coexpress-enrich_weighted-p10Coding_with-shared.pdf",
       width=10,height=15)
```


# Just the four relative tissues 


```{r}

keep.tissues <- c("Islet","Muscle...Skeletal","Liver","Adipose...Subcutaneous")
sub.df <- filter(w.df,tissue %in% keep.tissues)

plt2 <- plot_enrich_alt(sub.df,nrow1=TRUE)
ggsave(plot=plt2,filename = plot.dir %&% "coexpress-enrich_weighted-noCoding-fourtiss.png",width=15,height=7)
ggsave(plot=plt2,filename = plot.dir %&% "coexpress-enrich_weighted-noCoding-fourtiss.pdf",width=15,height=7)
```

# Plots if we include "sharing" category 

```{r}


keep.tissues <- c("Islet","Muscle...Skeletal","Liver","Adipose...Subcutaneous")
sub.df2 <- filter(w.df2,tissue %in% keep.tissues)
sub.df2$tissue <- gsub("Muscle...Skeletal","Muscle",sub.df2$tissue)
sub.df2$tissue <- gsub("Adipose...Subcutaneous","Adipose",sub.df2$tissue)
plt4 <- plot_enrich_alt2(sub.df2)
ggsave(plot=plt4,filename = plot.dir %&% "coexpress-enrich_weighted-noCoding-fourtiss_with-shared.png",width=8.5,height=2.5)
ggsave(plot=plt4,filename = plot.dir %&% "coexpress-enrich_weighted-noCoding-fourtiss_with-shared.pdf",width=8.5,height=2.5)
ggsave(plot=plt4,filename = plot.dir %&% "coexpress-enrich_weighted-noCoding-fourtiss_with-sharedEXTRA.pdf",width=8.5,height=10)
```



