---
title: "visualize-enrichments.Rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Setup 

```{r}

"%&%" <- function(a,b) paste0(a,b)


library("tidyverse")
library("data.table")
library("viridis")

serv.dir <- "/home/jason/science/servers/FUSE5/"

proj.dir <- serv.dir %&% "projects/t2d_classification/"
work.dir <- proj.dir %&% "revamp/"
plot.dir <- work.dir %&% "plots/"


```



# Physiology (hard clustering) enrichment 


```{r}

phys_enrich_plot <- function(enrich.df,myname,nc=4){
  plt <- ggplot(data=enrich.df,aes(x=tissue,y=enrichment)) + 
    geom_point(size=2,aes(fill=-log(p,base=10)),shape=21) + 
    facet_wrap(~physiology+threshold,ncol=nc) + 
    theme_bw() + 
    scale_fill_gradient2(low=viridis(n=50)[48],high=viridis(n=50)[10],
                         mid = viridis(n=50)[40],
                         midpoint=-log(0.05,base=10),
                         name=expression(-log10(p))) + 
    xlab("Classified Tissue") + ylab("Enrichment") + 
    ggtitle(myname) +
    theme(axis.text.x=element_text(vjust=0.6,angle=30),
          panel.grid.minor = element_blank(),
          panel.grid.major.x=element_blank(),
          legend.key = element_rect(color="black",size=3),
          strip.background =element_rect(fill="ghostwhite"),
          strip.text = element_text(colour = magma(n=2)[1]))
}



```

```{r}

mod_thresh <- function(enrich.df){
  enrich.df$threshold <- gsub("assigned_","0.",enrich.df$threshold)
  return(enrich.df)
}

df1b <- fread(work.dir %&% "analysis_files/phys71-enrich_weighted.txt") %>% mod_thresh(.)
df1b$physiology <- gsub("_"," ",df1b$physiology)

df2b <- fread(work.dir %&% "analysis_files/phys94-enrich_weighted.txt") %>% mod_thresh(.)
df2b$physiology <- gsub("_"," ",df2b$physiology)


plt1b <- phys_enrich_plot(df1b,myname="Physiology enrichment for classifed loci (weighted)")

plt2b <- phys_enrich_plot(df2b,myname="Physiology enrichment for classifed loci (weighted)")

ggsave(plot=plt1b,filename = plot.dir %&% "enrichment-phys_weighted-71.png",width=8,height=5)
ggsave(plot=plt2b,filename = plot.dir %&% "enrichment-phys_weighted-94.png",width=8,height=8)

ggsave(plot=plt1b,filename = plot.dir %&% "enrichment-phys_weighted-71.pdf",width=8,height=5)
ggsave(plot=plt2b,filename = plot.dir %&% "enrichment-phys_weighted-94.pdf",width=8,height=8)

```



## Version 2 


```{r}


phys_enrich_plot_v2 <- function(enrich.df,myname,nc=5){
  ggplot(data=enrich.df,aes(x=physiology,y=enrichment)) + 
    geom_point(size=2,aes(fill=-log(p,base=10)),shape=21) +
    facet_wrap(~tissue,ncol=nc) + 
    theme_bw() + 
    scale_fill_gradient2(low=viridis(n=50)[48],high=viridis(n=50)[10],
                         mid = viridis(n=50)[40],
                         midpoint=-log(0.05,base=10),
                         name=expression(-log10(p))) + 
    xlab("Classified Tissue") + ylab("Enrichment") + 
    ggtitle(myname) +
    theme(axis.text.x=element_text(vjust=0.6,angle=30),
          panel.grid.minor = element_blank(),
          panel.grid.major.x=element_blank(),
          legend.key = element_rect(color="black",size=3),
          strip.background =element_rect(fill="ghostwhite"),
          strip.text = element_text(colour = magma(n=2)[1]))
}



```


```{r}
df3b <- fread(work.dir %&% "analysis_files/phys71-enrich_weighted-V2.txt") %>% mod_thresh(.)
df3b$physiology <- gsub("_"," ",df3b$physiology)

df4b <- fread(work.dir %&% "analysis_files/phys94-enrich_weighted-V2.txt") %>% mod_thresh(.)
df4b$physiology <- gsub("_"," ",df4b$physiology)


plt3b <- phys_enrich_plot_v2(df3b,myname="Physiology enrichment for classifed loci (weighted)")
plt4b <- phys_enrich_plot_v2(df4b,myname="Physiology enrichment for classifed loci (weighted)")


ggsave(plot=plt3b,filename = plot.dir %&% "enrichment-phys_weighted-71-V2.png",width=8,height=3)
ggsave(plot=plt4b,filename = plot.dir %&% "enrichment-phys_weighted-94-V2.png",width=12,height=3)

ggsave(plot=plt3b,filename = plot.dir %&% "enrichment-phys_weighted-71-V2.pdf",width=8,height=3)
ggsave(plot=plt4b,filename = plot.dir %&% "enrichment-phys_weighted-94-V2.pdf",width=12,height=3)
```

