---
title: "Untitled"
author: "Jason Torres"
date: "1/14/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Setup 

```{r}
set.seed(1)

"%&%" <- function(a,b) paste0(a,b)

library("tidyverse")
library("data.table")
library("Homo.sapiens")
library("RColorBrewer")
library("grid");library("gridExtra")

serv.dir1 <- "/Users/jtorres/FUSE/"
serv.dir2 <- "/Users/jtorres/FUSE5/"

proj.dir <- serv.dir2 %&% "projects/t2d_classification/"


```



Load in GWAS file and calculate MAF for each SNP in the dataset 

```{r}

gwas.dir <- serv.dir1 %&% "reference/gwas/diamante-ukbb_hrc/"
gwas.df <- fread(gwas.dir %&% "ukbb_diamante-euro.bed") # will take a while to load, 0.681 GB file 
names(gwas.df) <- c("CHR","POS0","POS","SNPID","Freq","Z","PVAL","NCASE","NCONTROL")

pb <- txtProgressBar(min=0,max=dim(gwas.df)[1],style=3)
gwas.df$MAF <- map(1:dim(gwas.df)[1],function(i){
  setTxtProgressBar(pb,i)
  freq <- gwas.df$Freq[i]
  return(min(freq,1-freq))
}) %>% as.numeric(.)

#g.df <- dplyr::select(gwas.df,SNPID,MAF); g.df <- g.df[!duplicated(g.df),]

rare.snps <- filter(gwas.df, MAF < 0.005)$SNPID
low.freq.snps <- filter(gwas.df, MAF >= 0.005 & MAF < 0.05)$SNPID
high.freq.snps <- filter(gwas.df, MAF >= 0.05)$SNPID

```


# Prepare eqtl SNP vectors 


GTEx (Liver, Adipose, Muscle)


```{r}

gtex.dir <- serv.dir2 %&% "datasets/GTEx/v7/eqtl/GTEx_Analysis_v7_eQTL/"

liv.df <- fread("cat " %&% gtex.dir %&% "Liver.v7.signif_variant_gene_pairs.txt.gz" %&% " | zmore")
mus.df <- fread("cat " %&% gtex.dir %&% "Muscle_Skeletal.v7.signif_variant_gene_pairs.txt.gz" %&% " | zmore")
adi.df <- fread("cat " %&% gtex.dir %&% "Adipose_Subcutaneous.v7.signif_variant_gene_pairs.txt.gz" %&% " | zmore")

pb <- txtProgressBar(min=0,max=dim(liv.df)[1],style=3)
liv.eqtls <- map(1:length(liv.df$variant_id),function(i){
  setTxtProgressBar(pb,i)
  vec <- liv.df$variant_id[i] %>% strsplit(.,split="_")
  id <- "chr" %&% vec[[1]][1] %&% ":" %&% vec[[1]][2]
}) %>% as.character(.)

pb <- txtProgressBar(min=0,max=dim(mus.df)[1],style=3)
mus.eqtls <- map(1:length(mus.df$variant_id),function(i){
  setTxtProgressBar(pb,i)
  vec <- mus.df$variant_id[i] %>% strsplit(.,split="_")
  id <- "chr" %&% vec[[1]][1] %&% ":" %&% vec[[1]][2]
}) %>% as.character(.)

pb <- txtProgressBar(min=0,max=dim(adi.df)[1],style=3)
adi.eqtls <- map(1:length(adi.df$variant_id),function(i){
  setTxtProgressBar(pb,i)
  vec <- adi.df$variant_id[i] %>% strsplit(.,split="_")
  id <- "chr" %&% vec[[1]][1] %&% ":" %&% vec[[1]][2]
}) %>% as.character(.)

```


Islet (Oxford)

```{r}

islet.dir <- serv.dir1 %&% "reference/islet/eqtls/oxford/nominal_pass/output/"
islet.df <- fread("cat " %&% islet.dir %&% "snp_keyfile_fdr05.txt.gz" %&% " | zmore")
pb <- txtProgressBar(min=0,max=dim(islet.df)[1],style=3)
islet.eqtls <- map(1:dim(islet.df)[1],function(i){
  setTxtProgressBar(pb,i)
  vec <- c(islet.df$CHR[i],islet.df$POS[i])
  id <- vec[1] %&% ":" %&% vec[2]
}) %>% as.character(.)


```



# Developing enrichment functions 


Enrichment functions 

```{r}

get_overlap <- function(query.vec,eqtl.vec){
  sum(query.vec %in% eqtl.vec)
}

get_maf_matched_null_vec <- function(query.vec){
  sub.df <- filter(gwas.df,SNPID%in%query.vec)
  non.dup.df <- sub.df[!duplicated(sub.df$SNPID),]  # dup.df <- sub.df[duplicated(sub.df$SNPID),]
  maf.vec <- non.dup.df$MAF
  rare.count <- sum(maf.vec < 0.005)
  low.freq.count <- sum(maf.vec >= 0.005 & maf.vec < 0.05) # MAF >= 0.005 & MAF < 0.05
  high.freq.count <- sum(maf.vec >= 0.05) # MAF >= 0.05 
  rare.samp <- sample(rare.snps,size=rare.count,replace=FALSE)
  low.freq.samp <- sample(low.freq.snps,size=low.freq.count,replace=FALSE)
  high.freq.samp <- sample(high.freq.snps,size=high.freq.count,replace=FALSE)
  null.vec <- c(rare.samp,low.freq.samp,high.freq.samp)
  return(null.vec)
}

enrich_test <- function(query.vec,eqtl.vec,iter){
  obs <- get_overlap(query.vec,eqtl.vec)
  null.counts <- c()
  pb <- txtProgressBar(min=0,max=iter,style=3)
  for (i in 1:iter){
    setTxtProgressBar(pb,i)
    null.vec <- get_maf_matched_null_vec(query.vec)
    nullcount <- get_overlap(null.vec,eqtl.vec)
    null.counts <- append(null.counts,nullcount)
  }
  pval <- (sum(null.counts >= obs) + 1)/ (iter + 1)
  fac <- obs / mean(null.counts)
  out.df <- data.frame(observed=obs,enrichment=fac,pvalue=pval,stringsAsFactors = FALSE)
}

enrich_test_across_tissue <- function(query.vec,iter){
  print("islets..."); df1 <- enrich_test(query.vec,islet.eqtls,iter)
  print("liver..."); df2 <- enrich_test(query.vec,liv.eqtls,iter)
  print("adipose..."); df3 <- enrich_test(query.vec,adi.eqtls,iter)
  print("muscle..."); df4 <- enrich_test(query.vec,mus.eqtls,iter)
  out.df <- rbind(tissue=c("islet","liver","adipose","mucle"),df1,df2,df3,df4)
  out.df$tissue <- as.character(out.df$tissue)
  return(out.df)
}

```


Testing 

```{r}

#fcred.dir <- serv.dir2 %&% "projects/t2d_classification/method_A/multi_results/"
#fcred.df <- fread(fcred.dir %&% "results_func-cred-sets.txt")
#all.fcred.snps <- fcred.df$SNPID %>% unique(.) # length = 117522

#test.vec <- gwas.df$SNPID[sample(1:dim(gwas.df)[1],117522)]

#test.df <- enrich_test_across_tissue(test.vec,iter=100)
#enrich.df <- enrich_test_across_tissue(all.fcred.snps,iter=100)


```



# Determine thresholds 

```{r}


evaluate_threshold <- function(x,fcred.df,input.df,iter){
  # x is evaluated threshold
  classified <- map(input.df$Locus.ID,function(id){
    sub <- filter(input.df,Locus.ID==id) %>% dplyr::select(-one_of("Locus.ID")) %>% 
      sort(.,decreasing=TRUE) %>% as.data.frame(.)
    tiss <- names(sub)[1]
    val <- sub[,1]
    tiss <- ifelse(val>=x,tiss,"unclassified")
    return(tiss)
  }) %>% as.character(.)
  islet.loci <- input.df$Locus.ID[classified=="islet"]
  liver.loci <- input.df$Locus.ID[classified=="liver"]
  adipose.loci <- input.df$Locus.ID[classified=="adipose"]
  muscle.loci <- input.df$Locus.ID[classified=="muscle"]
  islet.snps <- filter(fcred.df,Locus.ID %in% islet.loci)$SNPID
  liver.snps <- filter(fcred.df,Locus.ID %in% liver.loci)$SNPID
  adipose.snps <- filter(fcred.df,Locus.ID %in% adipose.loci)$SNPID
  muscle.snps <- filter(fcred.df,Locus.ID %in% muscle.loci)$SNPID
  df1 <- enrich_test(islet.snps,islet.eqtls,iter)
  df2 <- enrich_test(liver.snps,liv.eqtls,iter)
  df3 <- enrich_test(adipose.snps,adi.eqtls,iter)
  df4 <- enrich_test(muscle.snps,mus.eqtls,iter)
  df0 <- data.frame(tissue=c("islet","liver","adipose","muscle"))
  out.df <- rbind(df1,df2,df3,df4)
  out.df <- cbind(df0,out.df)
  out.df$tissue <- as.character(out.df$tissue)
  out.df$threshold <- rep(x,dim(out.df)[1])
  return(out.df)
}

evaluate_thresholds <- function(x.vec=seq(0,1,0.05),fcred.df,input.df,iter){
  out.df <- c()
  for (x in x.vec){
    print("Threshold:");print(x)
    build.df <- evaluate_threshold(x,fcred.df,input.df,iter)
    out.df <- rbind(out.df,build.df)
  }
  return(out.df)
}

reformat_threshold_df <- function(thresh.df){
  out.df <- c()
  x.vec <- thresh.df$threshold %>% unique(.) %>% sort(.)
  pb <- txtProgressBar(min=0,max=length(x.vec),style=3)
  for (i in 1:length(x.vec)){
    setTxtProgressBar(pb,i)
    x <- x.vec[i]
    sub <- filter(thresh.df,threshold==x) %>% as.data.frame(.)
    build.df1 <- data.frame(threshold=x,
                           islet=filter(sub,tissue=="islet")$enrichment,
                           liver=filter(sub,tissue=="liver")$enrichment,
                           adipose=filter(sub,tissue=="adipose")$enrichment,
                           muscle=filter(sub,tissue=="muscle")$enrichment)
    build.df2 <- data.frame(threshold=x,
                           islet.nlpval=-log(filter(sub,tissue=="islet")$pvalue,base=10),
                           liver.nlpval=-log(filter(sub,tissue=="liver")$pvalue,base=10),
                           adipose.nlpval=-log(filter(sub,tissue=="adipose")$pvalue,base=10),
                           muscle.nlpval=-log(filter(sub,tissue=="muscle")$pvalue,base=10))
    build.df <- inner_join(build.df1,build.df2,by="threshold")
    out.df <- rbind(out.df,build.df)
  }
  return(out.df)
}


```


```{r}

select_classifier_threshold_plot <- function(plot.df){
  islet.col <- "green"; adipose.col <- "gold"; muscle.col <- "red"; liver.col <- "brown"
  val <- -log(0.05,base=10)
  sub.df <- filter(sub.df,islet.nlpval>val&liver.nlpval>val&adipose.nlpval>val&muscle.nlpval>val)
  plt <- ggplot(data=sub.df,aes(x=threshold)) + 
    geom_line(aes(y=islet),col=islet.col) + geom_point(aes(y=islet,size=islet.nlpval),shape=21,fill=islet.col) + 
    geom_line(aes(y=adipose),col=adipose.col) + geom_point(aes(y=adipose,size=adipose.nlpval),shape=21,fill=adipose.col) +     
    geom_line(aes(y=muscle),col=muscle.col) + geom_point(aes(y=muscle,size=muscle.nlpval),shape=21,fill=muscle.col) +     
    geom_line(aes(y=liver),col=liver.col) + geom_point(aes(y=liver,size=liver.nlpval),shape=21,fill=liver.col) + 
    theme_bw() + theme(legend.position ="none") + ggtitle("Tissue eQTL enrichments by threshold") + ylab("enrichment")
  
  max.islet <- arrange(sub.df,desc(islet))$threshold[1]
  max.adipose <- arrange(sub.df,desc(adipose))$threshold[1]
  max.muscle <- arrange(sub.df,desc(muscle))$threshold[1]
  max.liver <- arrange(sub.df,desc(liver))$threshold[1]
  
  selected.thresh <- mean(c(max.islet,max.adipose,max.muscle,max.liver))
  
  plot2.df <- data.frame(tissue=c("islet","liver","adipose","muscle"),max.threshold=c(max.islet,max.liver,max.adipose,max.muscle),
                         col=c(islet.col,liver.col,adipose.col,muscle.col),stringsAsFactors = FALSE)
  plt2 <- ggplot(data=plot2.df,aes(x=tissue,y=max.threshold)) +
    geom_bar(stat="identity",color="black",fill=c(adipose.col,islet.col,liver.col,muscle.col)) + 
    geom_hline(yintercept = selected.thresh,linetype=2) + 
    ggtitle("Selected threshold: " %&% selected.thresh) + theme_bw()
  
  out.plt<-grid.arrange(plt,plt2)
  #plt2
  return(out.plt)
}

```



# Run enrichment tests 

##  Method A 


```{r}

fcred.dir <- serv.dir2 %&% "projects/t2d_classification/method_A/multi_results/"
fcred.df <- fread(fcred.dir %&% "results_func-cred-sets.txt")
input.df <- fread(proj.dir %&% "method_A/analysis_files/test_input.txt")
#thresh.df <- evaluate_thresholds(x.vec=seq(0,1,0.05),fcred.df,input.df,iter=10)
thresh.df <- fread(proj.dir %&% "temp_thresh.txt")
plot.df <- reformat_threshold_df(thresh.df)

plt <- select_classifier_threshold_plot(plot.df) 
ggsave(plt,filename = proj.dir%&%"plots/methodA_select-thresh-eqlt.pdf",width=6,height=8)

```







