---
title: "visualize-enrichments.Rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Setup 

```{r}

"%&%" <- function(a,b) paste0(a,b)


library("tidyverse")
library("data.table")
library("viridis")


serv.dir <- "/Users/jasont/science/servers/FUSE5/"

proj.dir <- serv.dir %&% "projects/t2d_classification/"
work.dir <- proj.dir %&% "tactical_analyses/revisions/reviewer_1/"
plot.dir <- work.dir %&% "plots/"


```

General functions 

```{r}

simpleCap <- function(x) {
  s <- strsplit(x, " ")[[1]]
  paste(toupper(substring(s, 1,1)), substring(s, 2),
      sep="", collapse=" ")
}

firstup <- function(x) {
  substr(x, 1, 1) <- toupper(substr(x, 1, 1))
  x
}

```



# eQTL enrichment

```{r}

eqtl.df <- fread(work.dir%&%"enrichment_files/eqtls/eqtl_enrichment.txt")
eqtl.df$tissue_eqtl <- map(eqtl.df$tissue_eqtl,function(x){
  s <- strsplit(x, " ")[[1]]
  paste(toupper(substring(s, 1,1)), substring(s, 2),
      sep="", collapse=" ")
}) %>% as.character(.)
eqtl.df$tissue_toa <- map(eqtl.df$tissue_toa,function(x){
  s <- strsplit(x, " ")[[1]]
  paste(toupper(substring(s, 1,1)), substring(s, 2),
      sep="", collapse=" ") 
}) %>% as.character(.)


```


eQTL enrichment plot 

```{r}

eqtl.df$tissue_toa <- factor(eqtl.df$tissue_toa,
                             levels = c("Muscle","Adipose","Liver",
                                        "Islet","Shared","Unclassified"))
eqtl.df$tissue_eqtl <- factor(eqtl.df$tissue_eqtl,
                             levels = c("Muscle","Adipose.both","Adipose.sub",
                                        "Adipose.visc","Liver","Islet"))
```


```{r}

#eqtl.df <- filter(eqtl.df,!(tissue_eqtl %in% ex.vec))

eqtl.df$tissue_eqtl <- map(as.character(eqtl.df$tissue_eqtl),function(s){
  ifelse(s=="Inspire.gene","Islet (INSPIRE)",
         ifelse(s=="Islet_jmt","Islet (Oxford)",s))
}) %>% as.character(.) %>% as.factor(.)

eqtl.df$threshold <- map(eqtl.df$threshold,function(v){
  ifelse(v==0,0.0,
         ifelse(v==20,0.2,
                ifelse(v==50,0.5,
                       ifelse(v==80,0.8,NA))))
}) %>% as.numeric(.)

```


```{r}

eqtl_enrich_plot <- function(enrich.df,myname){
  enrich.df$threshold <- as.character(enrich.df$threshold)
  plt <- ggplot(data=enrich.df,aes(x=threshold,y=enrichment_snpsnap)) + 
    geom_point(color="black",shape=21,size=3,
               aes(fill=-log(pvalue_snpsnap,base=10))) + 
    facet_wrap(~tissue_eqtl+tissue_toa,ncol=6) + 
    theme_bw() + 
    scale_y_log10(breaks=c(0.5,2,10,50)) +
    scale_fill_gradient2(low=viridis(n=50)[48],high=viridis(n=50)[10],
                         mid = viridis(n=50)[40],
                         midpoint=-log(0.05,base=10),name=expression(-log10(p))) + 
    xlab("Threshold") + ylab("Enrichment") + 
    ggtitle(myname) +
    theme(axis.text.x=element_text(vjust=0.6),
          panel.grid.minor = element_blank(),
          panel.grid.major.x=element_blank(),
          legend.key = element_rect(color="black",size=0.5),
          strip.background =element_rect(fill="ghostwhite"),
          strip.text = element_text(colour = magma(n=2)[1]))

}
```

```{r}

plt <- eqtl_enrich_plot(eqtl.df,
                        myname="eQTL enrichment for classifed loci")
ggsave(plot=plt,filename = plot.dir %&%
         "enrichment-eqtl-expanded.png",width=8,height=8)
ggsave(plot=plt,filename = plot.dir %&%
         "enrichment-eqtl-expanded.pdf",width=8,height=8)

```


Only adipose results 

```{r}

plt2 <- eqtl_enrich_plot(filter(eqtl.df,
                                tissue_eqtl%in%c("Adipose.visc","Adipose.sub","Adipose.both")),
                        myname="eQTL enrichment for classifed loci")
ggsave(plot=plt2,filename = plot.dir %&%
         "enrichment-eqtl-adipose.png",width=8,height=4)
ggsave(plot=plt2,filename = plot.dir %&%
         "enrichment-eqtl-adipose.pdf",width=8,height=4)

```


All except Adipose(Both) category 


```{r}

plt3 <- eqtl_enrich_plot(filter(eqtl.df, tissue_eqtl!="Adipose.both"),
                        myname="eQTL enrichment for classifed loci")
ggsave(plot=plt3,filename = plot.dir %&%
         "enrichment-eqtl-addVisc.png",width=10,height=6)
ggsave(plot=plt3,filename = plot.dir %&%
         "enrichment-eqtl-addVisc.pdf",width=10,height=7)

```

