---
title: "R1.2.1_BMI-adjusted-evaluation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup 

```{r}

"%&%" <- function(a,b) paste0(a,b)

library("tidyverse")
library("data.table")

serv.dir <- "/Users/jasont/science/servers/FUSE5/"

proj.dir <- serv.dir %&% "projects/t2d_classification/"
work.dir <- proj.dir %&% "tactical_analyses/revisions/reviewer_1/"
plot.dir <- work.dir %&% "plots/"

ref.df <- fread(work.dir %&% "reference/mahajan_2018b_ST3.txt",header=F)
```

Process Mahajan 2018b Table S3 

```{r}

names(ref.df)[c(1,2,3,4,11,15,17)] <- c("nearest.gene","index.rsid","chrom","pos",
                                        "p.unadj","p.adj","het.p")
ref.df$p.unadj <- map(ref.df$p.unadj,function(s){
  gsub("x10","e",s) 
}) %>% as.numeric(.)
ref.df$p.adj <- map(ref.df$p.adj,function(s){
  gsub("x10","e",s) 
}) %>% as.numeric(.)
ref.df$het.p <- map(ref.df$het.p,function(s){
  gsub("x10","e",s) 
}) %>% as.numeric(.)
ref.df$pos <- map(ref.df$pos,function(s){
  gsub(",","",s) 
}) %>% as.integer(.)
het.df <- filter(ref.df,het.p < 0.00012)
het.sub <- filter(het.df,p.unadj < p.adj)
```


```{r}
toa.df <- fread(proj.dir %&%
    "tactical_analyses/analysis_files/classified-loci_weighted_with-shared.txt")
cred.df <- fread(proj.dir %&%
    "tactical_analyses/genetic_credible_sets/gencred.txt")
```

Build merged data frame 

```{r}

full.df <- c()
pb <- txtProgressBar(min=0,max=dim(het.df)[1],style=3)
for (i in 1:dim(het.df)[1]){
  setTxtProgressBar(pb,i)
  row.df <- het.df[i,]
  snp <- row.df$index.rsid
  signal <- filter(cred.df,lead.rsid==snp)$CondID %>% unique(.)
  build.df <- filter(toa.df,Locus.ID==signal)
  full.df <- rbind(full.df,build.df)
}

write.table(x=full.df,file=work.dir %&% "bmi-het-signals.txt",
            sep="\t",quote=F,row.names=F)

```

```{r}

full.sub <- c()
pb <- txtProgressBar(min=0,max=dim(het.sub)[1],style=3)
for (i in 1:dim(het.sub)[1]){
  setTxtProgressBar(pb,i)
  row.df <- het.sub[i,]
  snp <- row.df$index.rsid
  signal <- filter(cred.df,lead.rsid==snp)$CondID %>% unique(.)
  build.df <- filter(toa.df,Locus.ID==signal)
  full.sub <- rbind(full.sub,build.df)
}

write.table(x=full.sub,file=work.dir %&% "bmi-het-signals_26.txt",
            sep="\t",quote=F,row.names=F)

```


