---
title: "Untitled"
author: "Jason Torres"
date: "3/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup 

```{r}

"%&%" <- function(a,b) paste0(a,b)

library("tidyverse")
library("data.table")
library("Homo.sapiens")
library("grid");library("gridExtra")

#fuse.path <- "/Users/jtorres/"
fuse.path <- "/home/jason/science/servers/"
serv.dir <- fuse.path %&% "FUSE5/"
proj.dir <- serv.dir %&% "projects/t2d_classification/"
methA.dir <- proj.dir %&% "method_A/"
work.dir <- proj.dir %&% "method_C/"
analysis.dir <- work.dir %&% "analysis_files/"
plot.dir <- work.dir %&% "plots/"

cred.df <- fread(work.dir %&% "genetic_credible_sets/gencred.txt")


```


```{r}

map_condids <- function(df){
  Cond.ID <- map(1:dim(df)[1],function(i){
    filter(cred.df,Locus.ID==df$Locus.ID[i])$CondID %>% unique(.)
  }) %>% as.character(.)
  df$Locus.ID <- Cond.ID
  return(df)
}



unweighted.df <- fread(analysis.dir %&% "tissue_ppa_divvy-full-unweighted-unscaled.txt") %>% map_condids(.)
weighted.df <- fread(analysis.dir %&% "tissue_ppa_divvy-full-weighted-unscaled.txt") %>% map_condids(.) 
```


# append lead rsID info 

```{r}

append_rslead <- function(df){
  pb <- txtProgressBar(min=0,max=dim(df)[1],style=3)
  lead.rsid <- map(1:dim(df)[1],function(i){
      setTxtProgressBar(pb,i)
      id <- df$Locus.ID[i]
      filter(cred.df,CondID==id)$lead.rsid %>% unique(.)
    }) %>% as.character(.)
  df$lead.rsid <- lead.rsid
  return(df)
}


```



```{r}

stringToQuoser <- function(varName) {
  wrapr::let(c(VARNAME = varName), quo(VARNAME))
}

reformat_ppa_df <- function(ppa.df,cred.df){
  format.df <- c() 
  pb <- txtProgressBar(min=0,max=dim(ppa.df)[1],style=3)
  for (i in 1:dim(ppa.df)[1]){
    myrow <- ppa.df[i,] %>% as.data.frame(.)
    setTxtProgressBar(pb,i)
    Locus.ID <- rep(myrow$Locus.ID,length(2:length(myrow)))
    Annotation <- names(myrow)[2:length(myrow)]
    Proportion <- as.numeric(myrow[2:length(myrow)])
    stack.df <- data.frame(Locus.ID,Annotation,Proportion)
    format.df <- rbind(format.df,stack.df)
  }
  format.df$Annotation <- factor(format.df$Annotation,levels=names(ppa.df)[2:dim(ppa.df)[2]])
  
  Symbol <- c()
  pb <- txtProgressBar(min=0,max=dim(format.df)[1],style=3)
  for (i in 1:dim(format.df)[1]){
    setTxtProgressBar(pb,i)
    loc <- format.df$Locus.ID[i]
    symb <- filter(cred.df,CondID==loc)$symbol %>% unique(.)
    Symbol <- c(Symbol,symb)
  }
  format.df <- cbind(Symbol,format.df)  
  return(format.df)
}


```


```{r}

ppa_plot <- function(ppa.df,col.vec=c("olivedrab2","red","gold1","brown","grey"),
                     rankby="islet",number=NULL,leg=TRUE){
  rank.by <- stringToQuoser(rankby)
  append.df <- ppa.df
  append.df$PlotID <- map(ppa.df$Locus.ID,function(loc.id){
    sub <- filter(cred.df,CondID==loc.id) %>% dplyr::select(.,one_of("symbol","lead.rsid")) 
    sub <- sub[!duplicated(sub),]
    sub$symbol %&% " (" %&% sub$lead.rsid %&% ")"
    #loc.id %&% ": " %&% (filter(cred.df,CondID==loc.id)$symbol%>%unique(.))
  }) %>% as.character(.)
  
  format.df <- reformat_ppa_df(ppa.df,cred.df)
  format.df <- append_rslead(format.df)
  PlotID <- paste0(format.df$Symbol," (",format.df$lead.rsid, ")")
  plot.df <- cbind(PlotID,format.df)

  
  #ranklevs <- arrange(append.df,(!!rank.by))$PlotID
  ranklevs <- arrange(append.df,(!!rank.by))$PlotID

  plot.df$PlotID <- factor(plot.df$PlotID,levels=ranklevs)
  

  plot.df$PlotID <- factor(plot.df$PlotID, 
                           levels=levels(plot.df$PlotID))
  
  if(is.null(number)==FALSE){
    keep.ids <- arrange(append.df,desc(!!rank.by))$PlotID[1:number]
    plot.df <- filter(plot.df,PlotID %in% keep.ids)
  }
  
  plt <- ggplot(data=plot.df,aes(x=PlotID,
                                 y=Proportion,fill=Annotation)) + 
            geom_bar(stat="identity",color="black",size=0.2) + 
            scale_y_continuous(breaks=seq(0,1,0.1)) + 
            xlab("Locus") + 
            coord_flip() + 
            #scale_y_reverse() + 
            scale_fill_manual(values=col.vec) +
            ggtitle("Proportion of PPA attributable to each annotation\n" %&% rankby)
  if(leg==FALSE){
    plt <- plt + theme(legend.position = "none")
  }
  
  return(plt)
}

all_tissues_plot <- function(ppa.df,number=NULL,col.vec=c("olivedrab2","red","gold1","brown","grey")){
  plt1 <- ppa_plot(ppa.df,col.vec,rankby="islet",number,leg=FALSE)
  plt2 <- ppa_plot(ppa.df,col.vec,rankby="muscle",number,leg=FALSE)
  plt3 <- ppa_plot(ppa.df,col.vec,rankby="adipose",number,leg=FALSE)
  plt4 <- ppa_plot(ppa.df,col.vec,rankby="liver",number,leg=FALSE)
  plt5 <- ppa_plot(ppa.df,col.vec,rankby="other",number,leg=TRUE)  
  grob <- arrangeGrob(plt1,plt2,plt3,plt4,plt5,nrow=1)
}

```


Lookup loci with 100 SNP or fewer in credible set 

```{r}

df <- fread(analysis.dir %&% "tissue_ppa_divvy-full-weighted-unscaled_snpcount.txt")

keep.loci <- filter(df,snpcount<=100)$Locus.ID %>% unique(.)

```


Lookup loci with max PPA >= 0.50 


```{r}

df <- fread(analysis.dir %&% "maxppa.txt")
keep.vec <- filter(df,max.ppa >= 0.50)$Locus.ID %>% unique(.)

```



```{r}


grob1 <- all_tissues_plot(weighted.df,number=50)
ggsave(plot=grob1,filename=plot.dir%&%"stacked_barplots_full-weighted.png",width=25,height=15)

grob2 <- all_tissues_plot(unweighted.df,number=50)
ggsave(plot=grob2,filename=plot.dir%&%"stacked_barplots_full-unweighted.png",width=25,height=15)

grob3 <- all_tissues_plot(filter(weighted.df,Locus.ID%in%keep.loci),number=50)
ggsave(plot=grob3,filename=plot.dir%&%"stacked_barplots_snpcount100-weighted.png",width=27,height=12)

grob4 <- all_tissues_plot(filter(unweighted.df,Locus.ID%in%keep.loci),number=50)
ggsave(plot=grob4,filename=plot.dir%&%"stacked_barplots_snpcount100-unweighted.png",width=27,height=12)


grob5 <- all_tissues_plot(filter(weighted.df,Locus.ID%in%keep.vec),number=30)
ggsave(plot=grob5,filename=plot.dir%&%"stacked_barplots_maxppa50-weighted.png",width=25,height=8.5)
ggsave(plot=grob5,filename=plot.dir%&%"stacked_barplots_maxppa50-weighted.pdf",width=25,height=8.5)

grob6 <- all_tissues_plot(filter(unweighted.df,Locus.ID%in%keep.vec),number=30)
ggsave(plot=grob6,filename=plot.dir%&%"stacked_barplots_maxppa50-unweighted.png",width=27,height=12)


```


# Evaluate data frame 


```{r}

d <- filter(weighted.df,Locus.ID%in%keep.vec)

```


