---
title: "03.0_classify-loci.Rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

"%&%" <- function(a,b) paste0(a,b)

library("tidyverse")
library("data.table")
library("Homo.sapiens")

#fuse.path <- "/Users/jtorres/"
fuse.path <- "/home/jason/science/servers/"
serv.dir <- fuse.path %&% "FUSE5/"
proj.dir <- serv.dir %&% "projects/t2d_classification/"
work.dir <- proj.dir %&% "method_C/"
analysis.dir <- work.dir %&% "analysis_files/"
plot.dir <- work.dir %&% "plots/"

cred.df <- fread(work.dir %&% "genetic_credible_sets/gencred.txt")

enrich.dir <- work.dir %&% "enrichment_files/"

```


```{r}

#keep.df <- fread(proj.dir %&% "input_data/" %&% "380.locus.ID.txt")
#keep.vec <- keep.df$Locus.ID_inCREDS

weighted.df <- fread(analysis.dir %&% "tissue_ppa_divvy-full-weighted-unscaled.txt")
unweighted.df <- fread(analysis.dir %&% "tissue_ppa_divvy-full-unweighted-unscaled.txt")
#alt.df <- fread(analysis.dir %&% "tissue-scores-alternative_CodingNotRN.txt") #%>% 
  #filter(.,Locus.ID %in% keep.vec) 

```


# Classify function 

```{r}

build_classify_df <- function(ppa.df){
  pb <- txtProgressBar(min=0,max=dim(ppa.df)[1],style=3)
  assigned_00 <- c(); assigned_20 <- c(); assigned_50 <- c(); assigned_80 <- c()
  for (i in 1:dim(ppa.df)[1]){
    setTxtProgressBar(pb,i)
    row.df <- ppa.df[i,]
    val00 <- names(row.df[,2:6])[((row.df[,2:6]) >= 0.00) &
                          ((row.df[,2:6]) == max(row.df[,2:6]))]
    val20 <- names(row.df[,2:6])[((row.df[,2:6]) >= 0.20) &
                          ((row.df[,2:6]) == max(row.df[,2:6]))]
    val50 <- names(row.df[,2:6])[((row.df[,2:6]) >= 0.50) &
                          ((row.df[,2:6]) == max(row.df[,2:6]))]
    val80 <- names(row.df[,2:6])[((row.df[,2:6]) >= 0.80) &
                          ((row.df[,2:6]) == max(row.df[,2:6]))]
    val00 <- ifelse(length(val20)==0,"unclassified",val20)
    val20 <- ifelse(length(val20)==0,"unclassified",val20)
    val50 <- ifelse(length(val50)==0,"unclassified",val50)
    val80 <- ifelse(length(val80)==0,"unclassified",val80)
    assigned_00 <- c(assigned_00,val00)
    assigned_20 <- c(assigned_20,val20)
    assigned_50 <- c(assigned_50,val50)
    assigned_80 <- c(assigned_80,val80)
  }
  pb <- txtProgressBar(min=0,max=dim(ppa.df)[1],style=3)
  symbol <- map(1:dim(ppa.df)[1],function(i){
    setTxtProgressBar(pb,i)
    loc.id <- ppa.df$Locus.ID[i]
    filter(cred.df,Locus.ID==loc.id)$symbol %>% unique(.)
  }) %>% as.character(.)
  out.df <- cbind(ppa.df,assigned_00,assigned_20,assigned_50,assigned_80,symbol)
  out.df$assigned_00 <- as.character(out.df$assigned_00)
  out.df$assigned_20 <- as.character(out.df$assigned_20)
  out.df$assigned_50 <- as.character(out.df$assigned_50)
  out.df$assigned_80 <- as.character(out.df$assigned_80)
  out.df$symbol <- as.character(out.df$symbol)
  return(out.df)
}


make_bed_df <- function(prebed,tname){
  out.df <- dplyr::select(prebed,one_of("CHR","POS"))
  out.df$POS1 <- out.df$POS
  out.df <- out.df[!duplicated(out.df),]
  out.df$tissue <- tname 
  return(out.df)
}

save_classifed_snp_bedfiles <- function(class.df,type.name="unweighted"){
  df <- filter(cred.df,Locus.ID %in% (filter(class.df,assigned_20=="islet")$Locus.ID)) %>% make_bed_df(.,"islet")
  write.table(df,file=enrich.dir %&% type.name %&% "/" %&%type.name%&%"_islet_"%&%"thresh20.txt",sep="\t",quote=F,row.names=F,col.names=F)
  df <- filter(cred.df,Locus.ID %in% (filter(class.df,assigned_20=="adipose")$Locus.ID))  %>% make_bed_df(.,"adipose")
  write.table(df,file=enrich.dir %&% type.name %&% "/" %&%type.name%&%"_adipose_"%&%"thresh20.txt",sep="\t",quote=F,row.names=F,col.names=F)
  df <- filter(cred.df,Locus.ID %in% (filter(class.df,assigned_20=="liver")$Locus.ID))  %>% make_bed_df(.,"liver")
  write.table(df,file=enrich.dir %&% type.name %&% "/" %&%type.name%&%"_liver_"%&%"thresh20.txt",sep="\t",quote=F,row.names=F,col.names=F)
  df <- filter(cred.df,Locus.ID %in% (filter(class.df,assigned_20=="muscle")$Locus.ID))  %>% make_bed_df(.,"muscle")
  write.table(df,file=enrich.dir %&% type.name %&% "/" %&%type.name%&%"_muscle_"%&%"thresh20.txt",sep="\t",quote=F,row.names=F,col.names=F)
  
  df <- filter(cred.df,Locus.ID %in% (filter(class.df,assigned_50=="islet")$Locus.ID))  %>% make_bed_df(.,"islet")
  write.table(df,file=enrich.dir %&% type.name %&% "/" %&%type.name%&%"_islet_"%&%"thresh50.txt",sep="\t",quote=F,row.names=F,col.names=F)
  df <- filter(cred.df,Locus.ID %in% (filter(class.df,assigned_50=="adipose")$Locus.ID))  %>% make_bed_df(.,"adipose")
  write.table(df,file=enrich.dir %&% type.name %&% "/" %&%type.name%&%"_adipose_"%&%"thresh50.txt",sep="\t",quote=F,row.names=F,col.names=F)
  df <- filter(cred.df,Locus.ID %in% (filter(class.df,assigned_50=="liver")$Locus.ID))  %>% make_bed_df(.,"liver")
  write.table(df,file=enrich.dir %&% type.name %&% "/" %&%type.name%&%"_liver_"%&%"thresh50.txt",sep="\t",quote=F,row.names=F,col.names=F)
  df <- filter(cred.df,Locus.ID %in% (filter(class.df,assigned_50=="muscle")$Locus.ID))  %>% make_bed_df(.,"muscle")
  write.table(df,file=enrich.dir %&% type.name %&% "/" %&%type.name%&%"_muscle_"%&%"thresh50.txt",sep="\t",quote=F,row.names=F,col.names=F) 
  
  df <- filter(cred.df,Locus.ID %in% (filter(class.df,assigned_80=="islet")$Locus.ID))  %>% make_bed_df(.,"islet")
  write.table(df,file=enrich.dir %&% type.name %&% "/" %&%type.name%&%"_islet_"%&%"thresh80.txt",sep="\t",quote=F,row.names=F,col.names=F)
  df <- filter(cred.df,Locus.ID %in% (filter(class.df,assigned_80=="adipose")$Locus.ID))  %>% make_bed_df(.,"adipose")
  write.table(df,file=enrich.dir %&% type.name %&% "/" %&%type.name%&%"_adipose_"%&%"thresh80.txt",sep="\t",quote=F,row.names=F,col.names=F)
  df <- filter(cred.df,Locus.ID %in% (filter(class.df,assigned_80=="liver")$Locus.ID))  %>% make_bed_df(.,"liver")
  write.table(df,file=enrich.dir %&% type.name %&% "/" %&%type.name%&%"_liver_"%&%"thresh80.txt",sep="\t",quote=F,row.names=F,col.names=F)
  df <- filter(cred.df,Locus.ID %in% (filter(class.df,assigned_80=="muscle")$Locus.ID))  %>% make_bed_df(.,"muscle")
  write.table(df,file=enrich.dir %&% type.name %&% "/" %&%type.name%&%"_muscle_"%&%"thresh80.txt",sep="\t",quote=F,row.names=F,col.names=F)
  
  df <- filter(cred.df,Locus.ID %in% (filter(class.df,assigned_00=="islet")$Locus.ID))  %>% make_bed_df(.,"islet")
  write.table(df,file=enrich.dir %&% type.name %&% "/" %&%type.name%&%"_islet_"%&%"thresh00.txt",sep="\t",quote=F,row.names=F,col.names=F)
  df <- filter(cred.df,Locus.ID %in% (filter(class.df,assigned_00=="adipose")$Locus.ID))  %>% make_bed_df(.,"adipose")
  write.table(df,file=enrich.dir %&% type.name %&% "/" %&%type.name%&%"_adipose_"%&%"thresh00.txt",sep="\t",quote=F,row.names=F,col.names=F)
  df <- filter(cred.df,Locus.ID %in% (filter(class.df,assigned_00=="liver")$Locus.ID))  %>% make_bed_df(.,"liver")
  write.table(df,file=enrich.dir %&% type.name %&% "/" %&%type.name%&%"_liver_"%&%"thresh00.txt",sep="\t",quote=F,row.names=F,col.names=F)
  df <- filter(cred.df,Locus.ID %in% (filter(class.df,assigned_00=="muscle")$Locus.ID))  %>% make_bed_df(.,"muscle")
  write.table(df,file=enrich.dir %&% type.name %&% "/" %&%type.name%&%"_muscle_"%&%"thresh00.txt",sep="\t",quote=F,row.names=F,col.names=F)
}



```


```{r}


df1 <- build_classify_df(unweighted.df)
df2 <- build_classify_df(weighted.df)
#df3 <- build_classify_df(alt.df)


write.table(x=df1,file=analysis.dir%&%"classified-loci_unweighted.txt",
            sep="\t",quote=F,row.names=FALSE,col.names=TRUE)
save_classifed_snp_bedfiles(df1,type.name="unweighted")

write.table(x=df2,file=analysis.dir%&%"classified-loci_weighted.txt",
            sep="\t",quote=F,row.names=FALSE,col.names=TRUE)
save_classifed_snp_bedfiles(df2,type.name="weighted")

#write.table(x=df3,file=analysis.dir%&%"classified-loci_alternative.txt",
#            sep="\t",quote=F,row.names=FALSE,col.names=TRUE)

#table(df2$assigned_20)
#table(df1$assigned_20)
#table(df3$assigned_20)sl

#table(df2$assigned_50)
#table(df1$assigned_50)
#table(df3$assigned_50)

#table(df2$assigned_80)
#table(df1$assigned_80)
#table(df3$assigned_80)

```

