---
title: "03.2b_plot-gene-coexpression.Rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup 

```{r}

"%&%" <- function(a,b) paste0(a,b)
library("tidyverse")
library("GenomicRanges")
library("viridis")
library("data.table")
library("plyr")

serv.dir <- "/home/jason/science/servers/FUSE5/"
proj.dir <- serv.dir %&% "projects/t2d_classification/"

work.dir <- proj.dir %&% "method_C/"
analysis.dir <- work.dir %&% "analysis_files/"
plot.dir <- work.dir %&% "plots/"

w.df <- fread(analysis.dir %&% "coexpress-enrich_weighted.txt") %>% 
  na.omit(.)
u.df <- fread(analysis.dir %&% "coexpress-enrich_unweighted.txt") %>% 
  na.omit(.)

w.df2 <- fread(analysis.dir %&% "coexpress-enrich_weighted_noCoding.txt") %>% 
  na.omit(.)
w.df3 <- fread(analysis.dir %&% "coexpress-enrich_weighted_p10Coding.txt") %>% 
  na.omit(.)
```



```{r}

plot_enrich <- function(plot.df){
  plt <- ggplot(data=plot.df,aes(x=tissue,y=log_pval)) + 
    geom_point(size=3,aes(shape=geneset,fill=log_pval),
               alpha=0.7) + 
    geom_hline(yintercept = -log(0.05/54,base=10)) + 
    geom_hline(yintercept = -log(0.05,base=10),linetype=2) + 
    facet_wrap(~threshold) + 
    scale_shape_manual(name="Gene set",values=c(21,22,23,24)) +
    scale_fill_viridis(name="-log10(p)",direction = -1) + 
    ylab("-log10(p)") + xlab("Tissue") + 
    theme(axis.text.x=element_text(size=14),
          strip.text = element_text(size=17),
          axis.title=element_text(size=17),
          legend.key.size = unit(7,"line")) + 
    coord_flip() + 
    theme_bw()
  return(plt)
}

```


```{r}

plt1 <- plot_enrich(w.df)
ggsave(plot=plt1,filename = plot.dir %&% "coexpress-enrich_weighted-ALL.png",width=12,height=12)

plt2 <- plot_enrich(u.df)
ggsave(plot=plt2,filename = plot.dir %&% "coexpress-enrich_unweighted-ALL.png",width=12,height=12)

```


```{r}

filter(w.df,threshold==0.50) %>% arrange(.,perm.pvalue) %>% View(.)

```

# Filtering 

```{r}

plt3 <- plot_enrich(w.df2)
ggsave(plot=plt3,filename = plot.dir %&% "coexpress-enrich_weighted-noCoding.png",width=12,height=12)
ggsave(plot=plt3,filename = plot.dir %&% "coexpress-enrich_weighted-noCoding.pdf",width=16,height=12)

plt4 <- plot_enrich(w.df3)
ggsave(plot=plt4,filename = plot.dir %&% "coexpress-enrich_weighted-p10Coding.png",width=12,height=12)


```

# Just 0.2 

```{r}

plt3b <- plot_enrich(filter(w.df2,threshold==0.20))

ggsave(plot=plt3b,filename = plot.dir %&% "coexpress-enrich_weighted-noCoding20.png",width=6.5,height=9)
ggsave(plot=plt3b,filename = plot.dir %&% "coexpress-enrich_weighted-noCoding20.pdf",width=6.5,height=9)

```

