---
title: "Untitled"
author: "Jason Torres"
date: "3/13/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup 

```{r}

"%&%" <- function(a,b) paste0(a,b)
library("tidyverse")
library("GenomicRanges")
library("viridis")

library("plyr")

serv.dir <- "/Users/jtorres/FUSE5/"
proj.dir <- serv.dir %&% "projects/t2d_classification/"

work.dir <- proj.dir %&% "method_A/"
analysis.dir <- work.dir %&% "analysis_files/"
plot.dir <- work.dir %&% "plots/"

keep.df <- fread(proj.dir %&% "input_data/" %&% "380.locus.ID.txt")
keep.vec <- keep.df$Locus.ID_inCREDS

block.df <- fread(work.dir %&% "multi_results/results_blocks.txt")

```


Read data files 

```{r}

block.df <- fread(work.dir %&%"multi_results/results_blocks.txt",sep="\t")
fcred.df <- fread(work.dir %&%"multi_results/results_func-cred-sets.txt",sep="\t")

```


```{r}

TPM.merged.ranks <- readRDS(proj.dir%&%"input_data/TPM.merged.ranks.rds")
TPMs.tissues.rank.matrix <- readRDS(proj.dir%&%"input_data/TPMs.tissues.rank.matrix.rds")

```


# Functions 

testing

```{r}



```



```{r}


enrichment <- function(geneset, perms){
	#geneset_ens <- TPM.merged.ranks[TPM.merged.ranks$Symbol %in% geneset, "Gene"]
	#names(geneset_ens) <- geneset
	
	sub.df <- filter(TPM.merged.ranks,Symbol%in%geneset)
	geneset_ens <- sub.df$Gene
  names(geneset_ens) <- sub.df$Symbol
  
	# Calculate average expression to make null and random distributions
	TPM.merged.ranks_geneset <- TPM.merged.ranks[TPM.merged.ranks$Symbol %in% geneset, "ranks2"]
	names(TPM.merged.ranks_geneset) <- TPM.merged.ranks[TPM.merged.ranks$Symbol %in% geneset, "Gene"]
	#h(TPM.merged.ranks_geneset)

	# create null bg genes for creating null gene_sets
	random.bg.ens <- sapply(TPM.merged.ranks_geneset, function(x){
		up <- x-150
		down <- x+150
		sample_from <- TPM.merged.ranks[up:down, "Gene"]
		sample_from2 <- setdiff(sample_from, geneset_ens)
	}, simplify=FALSE)
	
	# Create random gene sets using ranks + and - 100 
	random.geneList.ens <- list()

	for (i in 1:perms){
		gene_set <- lapply(random.bg.ens, function(x){
		rand <- sample(x, 1)
		})
		random.geneList.ens[[i]] <- unlist(gene_set)
	}

	geneset.list.test.ens <- list()

	pb <- txtProgressBar(min = 1, max = perms, style = 3)
	for (i in 1:perms){
		setTxtProgressBar(pb, i)
		gene_set <- random.geneList.ens[[i]]
		gene_set <- gene_set[!is.na(gene_set)] # remove NAs
		lista <- lapply(TPMs.tissues.rank.matrix, function(tissue){
		tis <- tissue
		df2 <- tis[match(gene_set, rownames(tis)), ]
		df3 <- apply(df2[,-c(1:2)], 1, function(x){sum(x, na.rm=TRUE)})
	})
	geneset.list.test.ens[[i]] <- lista
	}
	close(pb)

	geneset.list.test.ens <- lapply(geneset.list.test.ens, function(x)ldply(x))
	geneset.list.test.ens.sum <- lapply(geneset.list.test.ens, function(x) apply(x[,-1], 1, sum) )

	geneset.true <- lapply(TPMs.tissues.rank.matrix, function(tissue){
	tis <- tissue
	data <- tis[match(geneset_ens, rownames(tis)), ]
	data <- apply(data[,-c(1:2)], 1, sum)
	})

	geneset.true.sum <- lapply(geneset.true, function(x){sum(x, na.rm=T)})

	res.lista = list()

	for (i in 1:54){
		perm.value = c()
		for (j in 1:perms){
			perm = geneset.list.test.ens.sum[[j]][i]
			perm.value = c(perm.value, perm)
		}
		res.lista[[i]] = perm.value
	}

	names(res.lista) = names(geneset.true)
	zim <- data.frame(tissue = names(geneset.true), perm.pvalue = -9, count = -9, log_pval = -9)
	for ( i in 1:length(res.lista)){
		zim[i,2] <- (sum(res.lista[[i]] <= geneset.true.sum[[i]])+1)/(length(res.lista[[i]])+1)
		zim[i,3] <- (sum(geneset.true.sum[[i]] >=res.lista[[i]])+1)
		zim[i,4] <- -log10(zim[i,2])
	}
	zim <- zim[order(zim$log_pval, decreasing = TRUE),]
	#ht(zim)
	return(zim)
}

build_plot_df <- function(islet.genes,muscle.genes,
                          liver.genes,adipose.genes){
  enrich.isl.df <- enrichment(islet.genes, 10000)
  enrich.mus.df <- enrichment(muscle.genes, 10000)
  enrich.liv.df <- enrichment(liver.genes, 10000)
  enrich.adi.df <- enrichment(adipose.genes, 10000)
  enrich.isl.df$geneset <- "islet"
  enrich.mus.df$geneset <- "muscle"
  enrich.liv.df$geneset <- "liver"
  enrich.adi.df$geneset <- "adipose"
  plot.df <- rbind(enrich.isl.df,enrich.mus.df,
                   enrich.adi.df,enrich.liv.df)  
  return(plot.df)
}


plot_enrich <- function(plot.df){
  plt <- ggplot(data=plot.df,aes(x=tissue,y=log_pval)) + 
    geom_point(shape=21,size=2,aes(fill=geneset)) + 
    geom_hline(yintercept = -log(0.05/54,base=10)) + 
    geom_hline(yintercept = -log(0.05,base=10),linetype=2) + 
    scale_fill_manual("Gene Set",values=c("gold1","olivedrab2","brown","red"))+
    ylab("-log10(p)") + xlab("Tissue") + 
    coord_flip()
  return(plt)
}




```





Get co-expression enrichments enrichments 

Full 

```{r}

full.df <- fread(analysis.dir  %&% "classified_full.txt")
islet.genes <- filter(full.df,assigned=="islet")$symbol %>% unique(.)
muscle.genes <- filter(full.df,assigned=="muscle")$symbol %>% unique(.)
liver.genes <- filter(full.df,assigned=="liver")$symbol %>% unique(.)
adipose.genes <- filter(full.df,assigned=="adipose")$symbol %>% unique(.)

plot.df <- build_plot_df(islet.genes,muscle.genes,
                         liver.genes,adipose.genes)

plt1 <- plot_enrich(plot.df)

```



