---
title: "partition"
author: "Jason Torres"
date: "10/4/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

"%&%" <- function(a,b) paste0(a,b)

library("tidyverse")
library("data.table")
library("GenomicRanges")

serv.dir <- "/Users/jtorres/FUSE/"

bed.dir <- serv.dir %&% "reference/chromatin_segmentation/varshney_2016/chromatin_states/" 
work.dir <- bed.dir %&% "partitioned/"


```



Prepare data frames 


```{r}

tiss.vec <- c("Islets","Adipose","SkeletalMuscle","Liver")
isl.df <- fread("cat " %&% bed.dir %&% "Islets.chromatinStates.bed.gz | zmore",sep="\t")
adi.df <- fread("cat " %&% bed.dir %&% "Adipose.chromatinStates.bed.gz | zmore",sep="\t")
mus.df <- fread("cat " %&% bed.dir %&% "SkeletalMuscle.chromatinStates.bed.gz | zmore",sep="\t")
liv.df <- fread("cat " %&% bed.dir %&% "Liver.chromatinStates.bed.gz | zmore",sep="\t")

isl.df$V4 <- isl.df$V4 %>% gsub("/","_",.)
adi.df$V4 <- adi.df$V4 %>% gsub("/","_",.)
mus.df$V4 <- mus.df$V4 %>% gsub("/","_",.)
liv.df$V4 <- liv.df$V4 %>% gsub("/","_",.)

```


Parition function 

```{r}

gr_to_df <- function(gr){
  df <- data.frame("chr"=seqnames(gr),"start"=start(gr),"end"=end(gr))
  df$chr <- as.character(df$chr)
  return(df)
}

partition_split <- function(query.vec = strong.enhancers, key.term = "strong_enhancer"){
  df1 <- filter(isl.df,V4 %in% query.vec) %>% select(one_of("V1","V2","V3")); gr1 <-GRanges(seqnames=df1$V1,IRanges(start=df1$V2,end=df1$V3))
  df2 <- filter(adi.df,V4 %in% query.vec) %>% select(one_of("V1","V2","V3")); gr2 <-GRanges(seqnames=df2$V1,IRanges(start=df2$V2,end=df2$V3))
  df3 <- filter(mus.df,V4 %in% query.vec) %>% select(one_of("V1","V2","V3")); gr3 <-GRanges(seqnames=df3$V1,IRanges(start=df3$V2,end=df3$V3))
  df4 <- filter(liv.df,V4 %in% query.vec) %>% select(one_of("V1","V2","V3")); gr4 <-GRanges(seqnames=df4$V1,IRanges(start=df4$V2,end=df4$V3))
  all.gr <- append(append(append(gr1,gr2),gr3),gr4)
  isl.spec <- reduce(gr1[!(gr1 %over% append(append(gr2,gr3),gr4))])
  adi.spec <- reduce(gr2[!(gr2 %over% append(append(gr1,gr3),gr4))])
  mus.spec <- reduce(gr3[!(gr3 %over% append(append(gr1,gr2),gr4))])
  liv.spec <- reduce(gr4[!(gr4 %over% append(append(gr1,gr2),gr3))])
  spec.gr <- append(append(append(isl.spec,adi.spec),mus.spec),liv.spec)
  shared.gr <- all.gr[!(all.gr %over% spec.gr)]
  islet.shared <- reduce(shared.gr[shared.gr %over% gr1])
  irpt.shared <- reduce(shared.gr[!(shared.gr %over% islet.shared)])
  annot.name <- "islet_specific_" %&% key.term
  out.df1 <- gr_to_df(isl.spec); out.df1$name <- annot.name ; write.table(out.df1,file=work.dir%&%annot.name%&%".bed",sep="\t",quote=F,row.names=F,col.names=F)
  annot.name <- "adipose_specific_" %&% key.term
  out.df2 <- gr_to_df(adi.spec); out.df2$name <- annot.name; write.table(out.df2,file=work.dir%&%annot.name%&%".bed",sep="\t",quote=F,row.names=F,col.names=F)
  annot.name <- "muscle_specific_" %&% key.term 
  out.df3 <- gr_to_df(mus.spec); out.df3$name <- annot.name; write.table(out.df3,file=work.dir%&%annot.name%&%".bed",sep="\t",quote=F,row.names=F,col.names=F)
  annot.name <- "liver_specific_" %&% key.term 
  out.df4 <- gr_to_df(liv.spec); out.df4$name <- annot.name; write.table(out.df4,file=work.dir%&%annot.name%&%".bed",sep="\t",quote=F,row.names=F,col.names=F)
  annot.name <- "islet_shared_" %&% key.term
  out.df5 <- gr_to_df(islet.shared); out.df5$name <- annot.name; write.table(out.df5,file=work.dir%&%annot.name%&%".bed",sep="\t",quote=F,row.names=F,col.names=F)
  annot.name <- "irpt_shared_" %&% key.term
  out.df6 <- gr_to_df(irpt.shared); out.df6$name <- annot.name; write.table(out.df6,file=work.dir%&%annot.name%&%".bed",sep="\t",quote=F,row.names=F,col.names=F)
  out.df <- bind_rows(out.df1,out.df2,out.df3,out.df4,out.df5,out.df6)
  return(out.df)
}

```

write bed files

```{r}

strong.enhancers <- c("9_Active_enhancer_1","10_Active_enhancer_2")
weak.enhancers <- c("11_Weak_enhancer")
repressed.regions <- c("16_Repressed_polycomb", "17_Weak_repressed_polycomb", "18_Quiescent_low_signal")
promoters <- c("1_Active_TSS","2_Weak_TSS","3_Flanking_TSS")
gene.transcription <- c("5_Strong_transcription","6_Weak_transcription")
bivalent.tss <- c("14_Bivalent_poised_TSS")
genic.enhancer <- c("8_Genic_enhancer")

df1 <- partition_split(strong.enhancers,key.term="strong_enhancer")
df2 <- partition_split(weak.enhancers,key.term="weak_enhancer")
df3 <- partition_split(repressed.regions,key.term="repressed")
df4 <- partition_split(promoters,key.term="promoter")
df5 <- partition_split(gene.transcription,key.term="gene_transcription")
df6 <- partition_split(bivalent.tss,key.term="bivalent_tss")
df7 <- partition_split(genic.enhancer,key.term="genic_enhancer")

bed.df <- bind_rows(df1,df2,df3,df4,df5,df6,df7)

bed.df$num <- as.integer(gsub("chr","",bed.df$chr)) 
bed.df <- bed.df %>% arrange(chr,start) %>% select(one_of("chr","start","end","name"))
write.table(bed.df,file=work.dir%&%"complete_isl-adi-mus-liv.partitioned.bed",quote=F,sep="\t",row.names=F,col.names=F)


```



